### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by extrawurst** [johnschug/rust-gpg-error#5]
it seems we have troubles getting this to build for windows (see https://github.com/extrawurst/gitui/pull/219). should it work? if so how? is it possible to add this to the projects CI for reference?

**Comment by johnschug** [comment]
The main issue for this is now gpg-rs/gpgme#31. Note you shouldn't need to depend on this crate directly as it's re-exported by the [gpgme crate](https://docs.rs/gpgme/0.9.2/gpgme/error/index.html).

**Comment by timvisee** [comment]
I'm also having issues building this on Windows.

The build script seems to fail because it calls `sh`.

```bash
  --- stderr
  running: "sh" "-c" "C:\\Users\\timvisee\\scoop\\apps\\gnupg\\2.2.27\\bin\\libgpg-error-0.dll --version"
  failed to execute command: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  Error: ()
```

Any comments on getting this to work?

**Comment by johnschug** [comment]
That's slightly odd. Are you setting any of the `LIBGPG_ERROR_*` environment variables? Also which version of the crate are you using? One of the methods the build script uses to detect an installation of GnuPG is running a shell script that is distributed alongside GnuPG. The `LIBGPG_ERROR_CONFIG` environment variable controls the path used for this script, and if set (and neither `LIBGPG_ERROR_LIBS` or `LIBGPG_ERROR_LIB_DIR` are set) then it is the **only** method that is attempted. On windows if it is none of those are set, the build script attempts to retrieve the location of the installation from the registry (`Install Directory` in `HKLM:\SOFTWARE\GnuPG`). Finally, if that fails it attempts to run the configuration script using a default name (`gpg-error-config`). 

Based on that output and the rules above, it appears that something set `LIBGPG_ERROR_CONFIG` to the location of the libgpg-error dll.
