### ISSUE TITLE
supply a changelog for incompatible semver bumps at least

### ISSUE THREAD

**Issue by dkg** [johnschug/rust-gpg-error#8]
Thanks for the recent updates to libgpg-error and gpgme.  I note that the versions incremented in a [semver](https://semver.org)-incompatible way (from 0.5.x to 0.6), which means every downstream project that depends on them will itself need to adjust its dependencies and confirm that it works with whatever API changes are supplied.

It would be useful to downstream projects if there were a changelog that made clear what adjustments they need to make when moving across a semver-incompatible version.

**Comment by johnschug** [comment]
I've added a list of breaking changes to the [release](https://github.com/gpg-rs/libgpg-error/releases/tag/v0.6.0) for the latest version.

**Comment by dkg** [comment]
thanks for this, @johnschug .  I'm kind of a rust+semver n00b, but i'm not sure i understand how this counts as an incompatibility.  Reading the release notes it looks like it changes its own internal requirements, but the API stays the same, no?

Does 6.0.0 change the API offered by `libgpg-error-sys`?  If not, why not leave it at the compatible 0.5.x level, rather than forcing any downstream reverse dep to twiddle the expected version number in their `Cargo.toml`?

If it doesn't change the API, does that mean that it's standard practice to count as a semver incompatibility anything that introduces a new dependency or new MSRV or something?
